### PR TITLE
Update to Traceur 0.0.79

### PR DESCRIPTION
**Pull request by ocombe**
Here is the code to make this plugin work with Traceur 0.0.79.

### CODE REVIEW

**Comment by peterjosling** [comment]
Surely by disabling source maps in Traceur we only get a mapping back to the output?

**Comment by ocombe** [comment]
well it works for me in chrome, in get the original file & the line
You should try, but enabling it doesn't work (if you find out why, let me know)

**Comment by peterjosling** [comment]
Okay, that's fine then - I'll merge now. Thanks for the PR and sorry for being so slow :)

**Comment by ocombe** [comment]
No problem, you should try it once before just in case :)

**Pull request merged**
